"""
Constants used across the AOD codebase.

Consolidates hardcoded values and configuration data.
"""

# Major vendor/platform domains excluded from zombie classification
# These are large platform providers whose domains appear in enterprise data
# but are not individually managed assets (e.g., google.com hosts many services)
VENDOR_PLATFORM_DOMAINS = {
    "google.com",
    "googleapis.com",
    "gstatic.com",
    "googlevideo.com",
    "googleusercontent.com",
    "microsoft.com",
    "microsoftonline.com",
    "azure.com",
    "live.com",
    "office.com",
    "office365.com",
    "sharepoint.com",
    "apple.com",
    "icloud.com",
    "amazon.com",
    "amazonaws.com",
    "cloudfront.net",
    "facebook.com",
    "fbcdn.net",
    "meta.com",
    "twitter.com",
    "x.com",
    "linkedin.com",
    "licdn.com",
    "github.com",
    "githubusercontent.com",
    "cloudflare.com",
    "cloudflare.net",
    "akamai.com",
    "akamaized.net",
    "fastly.net",
    "youtube.com",
    "youtu.be",
    "vimeo.com",
    "adobe.com",
    "typekit.net",
    "fonts.googleapis.com",
    "cdnjs.cloudflare.com",
    "unpkg.com",
    "jsdelivr.net",
}

# Infrastructure domains excluded from shadow/zombie SaaS reconciliation
# These represent tooling and infrastructure, not SaaS applications
INFRASTRUCTURE_DOMAINS = {
    "redis.io",
    "redis.com",
    "postgresql.org",
    "mysql.com",
    "mariadb.org",
    "docker.com",
    "docker.io",
    "kubernetes.io",
    "k8s.io",
    "nginx.org",
    "nginx.com",
    "apache.org",
    "golang.org",
    "go.dev",
    "python.org",
    "nodejs.org",
    "npmjs.com",
    "npmjs.org",
    "pypi.org",
    "rubygems.org",
    "maven.org",
    "gradle.org",
    "jenkins.io",
    "circleci.com",
    "travisci.com",
    "travis-ci.com",
    "terraform.io",
    "hashicorp.com",
    "vault.hashicorp.com",
    "consul.io",
    "nomad.io",
    "elastic.co",
    "elasticsearch.com",
    "elasticsearch.org",
    "mongodb.org",
    "mongodb.com",
    "couchdb.apache.org",
    "kafka.apache.org",
    "rabbitmq.com",
    "nats.io",
    "prometheus.io",
    "grafana.com",
    "influxdata.com",
    "rust-lang.org",
    "ruby-lang.org",
    "linux.org",
    "gnu.org",
}
